<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('questions')->insert([
            [
                'id' => 1,
                'questionaire' => 'SB',
                'factor' => 'membership',
                'question' => 'Siento que pertenezco a la comunidad informática.',
                'options_type' => 'agreement7',
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 2,
                'questionaire' => 'SB',
                'factor' => 'membership',
                'question' => 'Siento una conexión con la comunidad informática.',
                'options_type' => 'agreement7',
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 3,
                'questionaire' => 'SB',
                'factor' => 'acceptance+',
                'question' => 'Me sentí aceptadx.',
                'options_type' => 'agreement7',
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 4,
                'questionaire' => 'SB',
                'factor' => 'acceptance+',
                'question' => 'Me sentí respetadx.',
                'options_type' => 'agreement7',
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 5,
                'questionaire' => 'SB',
                'factor' => 'acceptance+',
                'question' => 'Me sentí valoradx.',
                'options_type' => 'agreement7',
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 6,
                'questionaire' => 'SB',
                'factor' => 'acceptance+',
                'question' => 'Me sentí apreciadx.',
                'options_type' => 'agreement7',
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 7,
                'questionaire' => 'SB',
                'factor' => 'acceptance-',
                'question' => 'Nunca me sentí desatentidx.',
                'options_type' => 'agreement7',
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 8,
                'questionaire' => 'SB',
                'factor' => 'acceptance-',
                'question' => 'Nadie fue negligente con mi aprendizaje o conmigo.',
                'options_type' => 'agreement7',
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 9,
                'questionaire' => 'SB',
                'factor' => 'acceptance-',
                'question' => 'Nunca me sentí excluidx.',
                'options_type' => 'agreement7',
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
        [
                'id' => 10,
                'questionaire' => 'SB',
                'factor' => 'acceptance-',
                'question' => 'Nunca me sentí insignificante.',
                'options_type' => 'agreement7',
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 11,
                'questionaire' => 'SB',
                'factor' => 'trust',
                'question' => 'Incluso cuando me iba mal, mis instructores tenían fe en mi potencial.',
                'options_type' => 'agreement7',
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 12,
                'questionaire' => 'SB',
                'factor' => 'trust',
                'question' => 'Mis instructores se comprometieron a ayudarme a aprender.',
                'options_type' => 'agreement7',
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 13,
                'questionaire' => 'SB',
                'factor' => 'trust',
                'question' => 'Sentí que no tenía que ponerme a prueba constantemente.',
                'options_type' => 'agreement7',
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 14,
                'questionaire' => 'SB',
                'factor' => 'trust',
                'question' => 'Sentí que los materiales de evaluación eran imparciales.',
                'options_type' => 'agreement7',
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 15,
                'questionaire' => 'SB',
                'factor' => 'membership',
                'question' => 'Siento que en este momento ya formo parte de la comunidad informática.',
                'options_type' => 'agreement7',
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            //SELF EFFICACY ---------------------------------
            [
                'id' => 16,
                'questionaire' => 'SE',
                'factor' => 'applyCurrentKnowledge',
                'question' => '¿Cómo te has sentido a lo largo de la carrera en cuanto a tu capacidad para aplicar los conocimientos y habilidades adquiridos en el campo de la informática?',
                'options_type' => 'seguridad5',
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 17,
                'questionaire' => 'SE',
                'factor' => 'applyCurrentKnowledge',
                'question' => '¿Con qué frecuencia te has sentido capaz de identificar y solucionar problemas técnicos complejos a lo largo de la carrera?',
                'options_type' => 'frecuencia5',
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 18,
                'questionaire' => 'SE',
                'factor' => 'applyCurrentKnowledge',
                'question' => '¿Cómo te has sentido a lo largo de la carrera en cuanto a tu capacidad para realizar investigaciones y análisis avanzados para resolver problemas técnicos en el campo de la informática?',
                'options_type' => 'seguridad5',
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 19,
                'questionaire' => 'SE',
                'factor' => 'applyCurrentKnowledge',
                'question' => '¿Con qué frecuencia te has sentido capaz de aplicar los conocimientos de la informática en situaciones prácticas y en el mundo real a lo largo de la carrera?',
                'options_type' => 'frecuencia5',
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 20,
                'questionaire' => 'SE',
                'factor' => 'effectiveCommunication',
                'question' => '¿Cómo te has sentido a lo largo de la carrera en cuanto a tu capacidad para comunicarte de manera efectiva con tus compañeros, profesores y otros profesionales en el campo de la informática?',
                'options_type' => 'seguridad5',
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 21,
                'questionaire' => 'SE',
                'factor' => 'effectiveCommunication',
                'question' => '¿Con qué frecuencia te has sentido seguro/a y capaz de presentar tus ideas y proyectos en público, tanto a nivel técnico como no técnico, a lo largo de la carrera?',
                'options_type' => 'frecuencia5',
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 22,
                'questionaire' => 'SE',
                'factor' => 'teamColab',
                'question' => '¿Cómo te has sentido a lo largo de la carrera en cuanto a tu capacidad para liderar y trabajar en equipo para resolver problemas técnicos en el campo de la informática?',
                'options_type' => 'seguridad5',
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 23,
                'questionaire' => 'SE',
                'factor' => 'teamColab',
                'question' => '¿Con qué frecuencia te has sentido motivado/a y enfocado/a al trabajar en proyectos técnicos en equipo y colaborar con otros profesionales en el campo de la informática a lo largo de la carrera?',
                'options_type' => 'frecuencia5',
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 24,
                'questionaire' => 'SE',
                'factor' => 'adquireKnowledge',
                'question' => '¿Cómo te has sentido a lo largo de la carrera en cuanto a tu capacidad para adaptarte y aprender nuevas tecnologías y herramientas (aprender un nuevo lenguaje, hacer un proyecto donde no sabes nada) en el campo de la informática?',
                'options_type' => 'seguridad5',
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 25,
                'questionaire' => 'SE',
                'factor' => 'previousKnowledge',
                'question' => '¿Cómo te sentiste al inicio de la carrera en cuanto a tus habilidades y conocimientos previos en el campo de la informática?',
                'options_type' => 'seguridad5',
                'deleted_at' => null,
                'created_at' => null,
                'updated_at' => null,
            ],

        ]);
    }
}
